config/routes.rb
Myproject::Application.routes.draw do
  resources :categories

  resources :contacts do
    collection do
      get 'contacts_list'
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  has_many :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :phone_number, :category_id
  
  belongs_to :category
  
  searchable do
    text :first_name
  end
 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    #raise params.inspect
     @categories = Category.all
    @search = Contact.search do
      fulltext params[:search]
     paginate :page => 1, :per_page => 3
    end
    @contacts = @search.results
   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
   
    #raise @categories.inspect
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    #raise params.inspect
    @contact = Contact.find(params[:id])

    respond_to do |format|
      #format.html # show.html.erb
      #format.json { render json: @contact }
      format.js
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new
    @categories = Category.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
      format.js
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
    @categories = Category.all
  end

  # POST /contacts
  # POST /contacts.json
  def create
    #raise params.inspect
    params[:contact].merge!(:category_id => params[:category])
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])
     params[:contact].merge!(:category_id => params[:category])
    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
  
  def contacts_list
    @result = []
    @contacts_list = Contact.where("first_name LIKE ?", "%#{params[:term]}%")
    @contacts_list.each do |contact|
      @result << Hash[:id => contact.id, :value => params[:term], :label => contact.first_name]
    end
    render json: @result
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Phone number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @category.contacts.each do |contact| %>
  <tr>
    <td><%= contact.first_name %></td>
    <td><%= contact.last_name %></td>
    <td><%= contact.email %></td>
    <td><%= contact.phone_number %></td>
    <td><%= link_to 'Show', contact %></td>
    <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
    <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/contacts/_data.html.erb
<table class="table">
      <tr>
        <th>First name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Phone number</th>
        <th>Category</th>
        <th></th>
        <th></th>
      </tr>

      <% @contacts.each do |contact| %>
        <tr>
          <td><%= link_to contact.first_name, "#contactPopupModal", :class => "contact-popup", :url => contact_path(contact.id) , "data-toggle" => "modal", :iid => contact.id %></td>
          <td><%= contact.last_name %></td>
          <td><%= contact.email %></td>
          <td><%= contact.phone_number %></td>
          <td class="success"><%= link_to contact.category.name, category_path(contact.category) if contact.category.present? %></td>
          <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
          <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>

        <div class="modal hide" id="contactPopupModal">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">✕</button>
            <h4><%= contact.first_name %></h4>
            <hr/>
            <div  id="contact-modal-body">

            </div>
          </div>
        </div>
      <% end %>
    </table>
    

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br />
    <%= f.text_field :phone_number %>
  </div>
  
  <div class="field">
    <%= f.label "Choose Category type"%>
    <%= select_tag "category", options_from_collection_for_select(@categories, :id, :name)%>
  </div>
  
  <div class="actions text-center">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/contacts/_new.html.erb
<%= render 'form' %>

app/views/contacts/_show.html.erb
<p class = "text-info">
  <b>First name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @contact.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Phone number:</b>
  <%= @contact.phone_number %>
</p>

<p>
  <b>Category</b>
  <%= @contact.category.name if @contact.category.present? %>
</p>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h2 class="text-success">Listing contacts</h2><hr/><br/>

<%= form_tag contacts_path, :method => :get  do %>
  <p>
  <%= text_field_tag :search, params[:search], :class =>"search-query", data: {autocomplete_source: contacts_list_contacts_path } %>
  <%= submit_tag "Search", :first_name => nil, :class => "btn btn-success" %>
  </p>
<% end %>
<div class="row-fluid">
  <div class="span6">
<%= render "data" %>
</div> 
 
   
  <div class="span2"></div>
  <div class="span4">
    <% @categories.each do |c| %>
      <%= link_to c.name, category_path(c)  %> (<%= c.contacts.count %>) <br/>
    <% end %>
  </div>
</div>

<br />

<%= link_to 'New Contact', "#newContactModal", :url => new_contact_path, :class => "btn btn-success new_contact", "data-toggle" => "modal" %>

 <div class="modal hide" id="newContactModal">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">✕</button>
            <h4>New Contact Form</h4>
            <hr/>
            <div  id="new-contact-modal-body">

            </div>
          </div>
        </div>

<script type="text/javascript"> 
  $('.search-query').autocomplete({
    source: $('.search-query').data('autocomplete-source'),
    select: function(event, ui){
    //$('.company_id').val(ui.item.id);
    $('.search-query').val(ui.item.label);		
    return false;
    }
  });
</script>

<script type="text/javascript">
  $('.contact-popup').click(function(){ 
      var url = $(this).attr("url");
      var contact_id = $(this).attr("iid");
      $.ajax({
        type: "GET",
        url: url,
        dataType: "script"
      });
  });
</script>

<script type="text/javascript">
  $('.new_contact').click(function(){ 
      var url = $(this).attr("url");
      $.ajax({
        type: "GET",
        url: url,
        dataType: "script"
      });
  });
</script>

app/views/contacts/new.js.erb
$("#new-contact-modal-body").html("<%= escape_javascript(render("new")) %>");

app/views/contacts/show.js.erb
 $("#contact-modal-body").html("<%= escape_javascript(render("show")) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myproject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class ="span12">
    <%= yield %>
  </div>
</div>
</body>
</html>